COUNTRYLIST = {
    "Adolf Hitler, German Reich": "https://i.dailymail.co.uk/i/pix/2018/02/10/21/22A81CE000000578-5376097-image-a-27_1518296535231.jpg",
    "Benito Mussolini, Italy": "https://4.bp.blogspot.com/-xH7wD--RARA/T25V3AIDEoI/AAAAAAAAAN0/zLZNt_UUveA/s1600/10.jpg",
    "Hirohito, Japan": "https://media.gettyimages.com/photos/japanese-emperor-hirohito-in-military-uniform-picture-id517391824?k=6&m=517391824&s=612x612&w=0&h=HUMMHkryzV3eGSGvVJuUAtMc-rLvhFOp2IQQLji5Xgc=",
    "Joseph Stalin, Soviet Union": "https://digilander.libero.it/blog.stronzate/IosifStalin.jpg",
    "Pierre Laval, France": "https://alchetron.com/cdn/pierre-laval-06354a50-6e2d-4c51-9e84-503453ddf63-resize-750.jpeg",
    "Stanley Baldwin, United Kingdom": "https://collectionimages.npg.org.uk/large/mw53418/Stanley-Baldwin.jpg",
    "Franklin D. Roosevelt, United States": "https://academiaparaninfo.wordpress.com/wp-content/uploads/2013/01/franklin-d-roosevelt-03.jpg",
    "Mohammad Zahir Shah, Afghanistan": "https://en.wikipedia.org/wiki/Mohammad_Zahir_Shah#/media/File:King_Zahir_Shah_of_Afghanistan_in_1963.jpg",
    "Zog I, Albania": "https://cbsnews1.cbsistatic.com/hub/i/2009/10/09/5c87b841-a642-11e2-a3f0-029118418759/image5374830.jpg",
    "Agustin Pedro Justo, Argentina": "https://www.lincheap.com/wp-content/uploads/2022/06/IMG_20220628_163745.jpg",
    "Mahammad Yayyo (unable to find picture), Sultanate of Aussa": "https://en.wikipedia.org/wiki/Sultanate_of_Aussa#/media/File:Red_flag.svg",
    "Joseph Lyons, Australia": "https://www.naa.gov.au/sites/default/files/styles/carousel_single_image_display/public/2020-07/pm-lyons-before-office-opening-of-16th-parliament-3149826.jpg?itok=FJwFdIDi",
    "Kurt Schuschnigg, Austria": "https://media.gettyimages.com/photos/kurt-schuschnigg-11th-chancellor-of-austria-circa-1935-picture-id954624874?k=6&m=954624874&s=612x612&w=0&h=7Nd1_bnFiP7FmRSoh2SxCGYY0AV0DRdyO1FKB58Zo5A=",
    "Paul van Zeeland, Belgium": "https://m.media-amazon.com/images/I/81B5k2J05RL._AC_SL1500_.jpg",
    "Jigme Wangchuck, Bhutan": "https://en.wikipedia.org/wiki/List_of_rulers_of_Bhutan#/media/File:Bhutan-Jigme-Wangchuck.jpg",
    "Jose Luis Tejada Sorzano, Bolivian Republic": "https://www.ibolivia.org/wp-content/uploads/2019/09/jose-luis-tejada-sorzano.jpg",
    "Getulio Vargas, Brazil": "https://www.historynet.com/wp-content/uploads/2022/10/getulio-vargas-brazilian-president-mh-winter-2023-1021x1536.jpg",
    "Shenton Thomas, British Malaya": "https://collectionimages.npg.org.uk/large/mw52645/Sir-Thomas-Shenton-Whitelegge-Thomas.jpg",
    "Willingdon (Linlithgow in game - he didn't become the governor until April), British Raj": "https://en.wikipedia.org/wiki/Freeman_Freeman-Thomas,_1st_Marquess_of_Willingdon#/media/File:Freeman_Freeman-Thomas_by_Henry_Walter_Barnett.jpg",
    "Boris III, Bulgaria": "https://cdn.britannica.com/43/76543-050-237F3206/Boris-III.jpg",
    "William Mackenzie King, Dominion of Canada": "https://d2kdkfqxnvpuu9.cloudfront.net/images/giant/78031.jpg?1532342723",
    "Arturo Alessandri, Chile": "https://media.lex.dk/media/158030/standard_Arturo_Alessandri_Palma_en_1925.jpg",
    "Chiang Kai-Shek, China": "https://2.bp.blogspot.com/-EB8nDjZEwJI/TuAY0WNSpyI/AAAAAAAAC50/7zK7Yufv7J8/s1600/Chiang+Kai-shek+V.jpg",
    "Colombia": "https://farm5.staticflickr.com/4113/5184941825_8360a39cfc_z.jpg",
    "Mao Zedong, Communist China": "https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/mao-tse-tung-portrait-bettmann.jpg",
    "Ricardo Jimenez Oreamuno, Costa Rica": "https://prabook.com/web/show-photo.jpg?id=1500768",
    "Jose Agripino Barnet, Cuba": "https://historymaps.info/images/1940.png",
    "Edvard Benes, Czechoslovakia": "https://media.gettyimages.com/photos/portrait-of-czechoslovakian-politician-edvard-benes-1930s-picture-id174305241?k=6&m=174305241&s=612x612&w=0&h=KQmlOb_sF6e-JvcCNfWmT26mdnhNHZqhM_dp5mfbsA8=",
    "Thorvald Stauning, Denmark": "https://media.snl.no/media/194379/standard_Stauning_i1920-erne_1_.jpg",
    "Rafael Trujillo, Dominican Republic": "https://i5.walmartimages.com/asr/60b4ab9c-c6e2-4790-bc93-51c2f8f2d612_1.aa405431017ddccb483e52b088e7f477.jpeg",
    "Bonifacius Cornelis de Jonge, Dutch East Indies": "https://en.wikipedia.org/wiki/Bonifacius_Cornelis_de_Jonge#/media/File:Portrait_of_Jonkheer_Bonifacius_Cornelis_de_Jonge_by_Jan_Frank_Ministry_of_the_Interior_and_Kingdom_Relations.jpg",
    "Federico Paez, Ecuador": "https://www.enciclopediadelecuador.com/wp-content/uploads/2016/05/Ing_Federico_Paez.jpg",
    "Maximiliano Hernandez Martinez, El Salvador": "https://media.gettyimages.com/photos/portrait-between-approximately-1931-and-1937-of-the-general-and-of-picture-id105218372?k=6&m=105218372&s=612x612&w=0&h=grCdkAaTFGtCFWnXHNfXmPSEt_2Ozxm8ywDSg9UOkjE=",
    "Konstantin Pats, Estonia": "https://media.gettyimages.com/photos/portrait-of-estonia-head-of-state-konstantin-pats-1939-picture-id505811222?k=6&m=505811222&s=612x612&w=0&h=t16YheBgylYNXbYo-3UO3w4IV_5ttQpxot1qf_zEPUY=",
    "Haile Selassie, Ethiopia": "http://bih-x.info/wp-content/uploads/2017/08/Haile-Selassie.jpg",
    "Pehr Evind Svinhufvud, Finland": "https://en.wikipedia.org/wiki/List_of_presidents_of_Finland#/media/File:President_of_Finland_Pehr_Evind_Svinhufvud.jpg",
    "Konstantinor Demertzis, Kingdom of Greece": "https://alchetron.com/cdn/konstantinos-demertzis-db250750-a860-484b-86b3-e8d9071292a-resize-750.jpg",
    "Li Zongren, Guangxi Clique": "https://p5.toutiaoimg.com/details/v1/w640/pgc-image/dafc0fd1011142a095fbf7703c727b67.awebp?from=detail",
    "Jorge Ubico, Guatemala": "https://en-academic.com/pictures/enwiki/71/General-Jorge-Ubico.jpg",
    "Stenio Vincent, Haiti": "https://alchetron.com/cdn/stnio-vincent-949bd4cd-d1d8-4109-b3ee-27a82b0debd-resize-750.jpeg",
    "Tiburcio Carias Andino, Honduras": "https://media.gettyimages.com/id/514908104/photo/general-tiburcio-andino-honduran-president.jpg?s=1024x1024&w=gi&k=20&c=b0-ttljHIEMaVWFLrbXBmhbw0l1QXOL7VQWakgOC46k=",
    "Miklos Horthy, Kingdom of Hungary": "https://cdn.prod.www.spiegel.de/images/2fcf1502-0001-0004-0000-000001242238_w1600_r0.718_fpx50_fpy61.74.jpg",
    "Hermann Jonasson, Iceland": "https://www.althingi.is/myndir/mynd/thingmenn/249/org/mynd.jpg",
    "Reza Shah, Iran": "https://en.wikipedia.org/wiki/Reza_Shah#/media/File:Reza_shah_uniform.jpg",
    "Yasin al-Hashimi, Iraq": "https://en.wikipedia.org/wiki/Yasin_al-Hashimi#/media/File:Yasin_Hashimi,_1927.jpg",
    "Eamon de Valera, Ireland": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/De_Valera_LCCN2016822004_(headshot).jpg/640px-De_Valera_LCCN2016822004_(headshot).jpg?Eamon_de_Valera66281741",
    "Alberts Kviesis, Latvia": "https://www.famousbirthdays.com/faces/kviesis-alberts-image.jpg",
    "Edwin Barclay, Liberia": "https://vignette.wikia.nocookie.net/kaiserreich/images/7/79/EdwinBarclay.jpeg/revision/latest/scale-to-width-down/210?cb=20200611191349",
    "Antanas Smetona, Lithuania": "https://i5.walmartimages.com/asr/afe752c6-fd31-4f37-9111-12b0603f9d4a_1.9238b9b31b564536b4a946692dcc356f.jpeg",
    "Joseph Bech, Luxembourg": "https://media.snl.no/media/56549/standard_Joseph_Bech_1933.jpg",
    "Puyi, Manchukuo": "https://en.wikipedia.org/wiki/Puyi#/media/File:Pu_Yi,_Qing_dynasty,_China,_Last_emperor.jpg",
    "Yondonwangchug, Mengkukuo (Technically at time was Mongol Military Government)": "https://kids.kiddle.co/images/b/bd/Yun_Wang.jpg",
    "Lazaro Cardenas del Rio, Mexico": "https://www.thoughtco.com/thmb/RCIk6dZvUoVbdHvE1mnTmbgXdUo=/2566x3680/filters:fill(auto,1)/General_L-zaro_C-rdenas_del_R-o-56a58abb3df78cf77288ba9d.jpg",
    "Anandyn Amar, Mongolia": "https://pantheon.world/images/profile/people/1273444.jpg",
    "Tribhuvan Bir Bikram Shah, Nepal": "https://en.wikipedia.org/wiki/Tribhuvan_of_Nepal#/media/File:King_Tribhuvan_(cropped).png",
    "Hendrikus Colijn, Netherlands": "https://images0.persgroep.net/rcs/oigqgROv9uQBK91JADu-v_CwmMA/diocontent/201479807/_fitwidth/763?appId=93a17a8fd81db0de025c8abd1cca1279&quality=0.8",
    "Michael Joseph Savage, New Zealand": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Michael_Joseph_Savage_Portrait_(cropped).jpg/440px-Michael_Joseph_Savage_Portrait_(cropped).jpg",
    "Juan Bautista Sacasa, Nicaragua": "https://en.wikipedia.org/wiki/Juan_Bautista_Sacasa#/media/File:Juan_Bautista_Sacasa_cph.3a44780.jpg",
    "Johan Nygaardsvold, Norway": "https://en.wikipedia.org/wiki/Johan_Nygaardsvold#/media/File:Johan_Nygaardsvold_1934.jpeg",
    "Said bin Taimur, Oman": "https://en.wikipedia.org/wiki/Said_bin_Taimur#/media/File:Said_bin_Taimur_(cropped).png",
    "Harmodio Arias Madrid, Panama": "https://www.biografiasyvidas.com/biografia/a/fotos/arias_harmodio.jpg",
    "Eusebio Ayala, Republic of Paraguay": "https://en.wikipedia.org/wiki/Eusebio_Ayala#/media/File:Eusebio_Ayala_retrato.jpg",
    "Oscar Benavides, Peru": "https://prabook.com/web/show-photo.jpg?id=1500255",
    "Manuel Quezon, Philippines": "https://en.wikipedia.org/wiki/Manuel_L._Quezon#/media/File:Manuel_L._Quezon_(November_1942).jpg",
    "Ignacy Moscicki, Poland": "https://cdn.britannica.com/12/133912-050-133E81E8/Ignacy-Moscicki.jpg",
    "Antonio de Oliveira Salazar, Portugal": "https://c1.staticflickr.com/9/8218/8313183867_b9d1de79ec_b.jpg",
    "Gheorghe Tatarescu, Romania": "https://alchetron.com/cdn/gheorghe-ttrescu-09891028-e2aa-4020-b897-206cf23372f-resize-750.jpeg",
    "Ibn Saud, Saudi Arabia": "https://cdn.britannica.com/35/10835-050-F37ECEB0/Ibn-Saud-kingdom-Saudi-Saudi-Arabia-country.jpg",
    "Yan Xishan, Shanxi": "https://en.wikipedia.org/wiki/Yan_Xishan#/media/File:Yan_Xishan.jpg",
    "Phraya Phahon Phonphayuhasena, Siam": "https://i.pinimg.com/originals/11/30/e2/1130e27b15593ac0ad260f012dceb4fa.jpg",
    "Ma Zhongying, Sinkiang": "https://alchetron.com/cdn/ma-zhongying-141792d0-9d79-41ab-95e9-3c72a08994e-resize-750.jpg",
    "J.B.M. Hertzog, South Africa": "https://vignette.wikia.nocookie.net/totalwar-ar/images/2/29/J.B.M._Hertzog.jpg/revision/latest?cb=20180520204722",
    "Francisco Franco, Spain": "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-760w,f_auto,q_auto:best/newscms/2019_39/3023096/190924-francisco-franco-cs-735a.jpg",
    "Axel Pehrsson-Bramstorp, Sweden": "https://en.wikipedia.org/wiki/Axel_Pehrsson-Bramstorp#/media/File:Axel_Pehrsson-Bramstorp.jpg",
    "Albert Meyer, Switzerland": "https://prabook.com/web/show-photo.jpg?id=23913",
    "Adyg Tyulush Chulydum (no picture), Tannu Tuva": "https://qph.cf2.quoracdn.net/main-qimg-9ffd1ef7ec255b2a468710921dcd3bce",
    "Jamphel Yeshe Gyaltsen, Tibet": "https://qph.cf2.quoracdn.net/main-qimg-9ffd1ef7ec255b2a468710921dcd3bce",
    "Mustafa Kemel Ataturk, Turkey": "https://www.thoughtco.com/thmb/YkmGSzPhLqf1sAqVyO2m19jpSiE=/2537x3775/filters:fill(auto,1)/AtaturkCentralPressGettyImages1925-56a040965f9b58eba4af89b5.jpg",
    "Gabriel Terra, Uruguay": "https://el-pais.brightspotcdn.com/uploads/2019/06/21/5d0d4acf1d704.jpeg",
    "Eleazar Contreras, Venezuela": "https://www.biografiasyvidas.com/biografia/l/fotos/lopez_contreras.jpg",
    "Xibei San Ma": "https://de-academic.com/pictures/dewiki/77/Ma_Bufang.jpg",
    "Imam Yahya, Yemen": "https://en.wikipedia.org/wiki/Yahya_Muhammad_Hamid_ed-Din#/media/File:Imam_yahya_cropped.png",
    "Prince Paul, Yugoslavia": "https://en.wikipedia.org/wiki/Prince_Paul_of_Yugoslavia#/media/File:Prince_Paul_of_Yugoslavia.jpg",
    "Li Yuanhong, Yunnan": "https://en.wikipedia.org/wiki/Li_Yuanhong#/media/File:Li_Yuanhong.jpg"  
}