COUNTRYLIST = {
    "Adolf Hitler, German Reich": "https://i.dailymail.co.uk/i/pix/2018/02/10/21/22A81CE000000578-5376097-image-a-27_1518296535231.jpg",
    "Benito Mussolini, Italy": "https://4.bp.blogspot.com/-xH7wD--RARA/T25V3AIDEoI/AAAAAAAAAN0/zLZNt_UUveA/s1600/10.jpg",
    "Hirohito, Japan": "https://media.gettyimages.com/photos/japanese-emperor-hirohito-in-military-uniform-picture-id517391824?k=6&m=517391824&s=612x612&w=0&h=HUMMHkryzV3eGSGvVJuUAtMc-rLvhFOp2IQQLji5Xgc=",
    "Joseph Stalin, Soviet Union": "https://digilander.libero.it/blog.stronzate/IosifStalin.jpg",
    "Pierre Laval, France": "https://alchetron.com/cdn/pierre-laval-06354a50-6e2d-4c51-9e84-503453ddf63-resize-750.jpeg",
    "Stanley Baldwin, United Kingdom": "https://collectionimages.npg.org.uk/large/mw53418/Stanley-Baldwin.jpg",
    "Franklin D. Roosevelt, United States": "https://academiaparaninfo.wordpress.com/wp-content/uploads/2013/01/franklin-d-roosevelt-03.jpg",
    "Mohammad Zahir Shah, Afghanistan": "https://en.wikipedia.org/wiki/Mohammad_Zahir_Shah#/media/File:King_Zahir_Shah_of_Afghanistan_in_1963.jpg",
    "Zog I, Albania": "https://cbsnews1.cbsistatic.com/hub/i/2009/10/09/5c87b841-a642-11e2-a3f0-029118418759/image5374830.jpg",
    "Agustin Pedro Justo, Argentina": "https://www.lincheap.com/wp-content/uploads/2022/06/IMG_20220628_163745.jpg",
    "Mahammad Yayyo (unable to find picture), Sultanate of Aussa": "https://en.wikipedia.org/wiki/Sultanate_of_Aussa#/media/File:Red_flag.svg",
    "Joseph Lyons, Australia": "https://www.naa.gov.au/sites/default/files/styles/carousel_single_image_display/public/2020-07/pm-lyons-before-office-opening-of-16th-parliament-3149826.jpg?itok=FJwFdIDi",
    "Kurt Schuschnigg, Austria": "https://media.gettyimages.com/photos/kurt-schuschnigg-11th-chancellor-of-austria-circa-1935-picture-id954624874?k=6&m=954624874&s=612x612&w=0&h=7Nd1_bnFiP7FmRSoh2SxCGYY0AV0DRdyO1FKB58Zo5A=",
    "Paul van Zeeland, Belgium": "https://m.media-amazon.com/images/I/81B5k2J05RL._AC_SL1500_.jpg",
    "Jigme Wangchuck, Bhutan": "https://en.wikipedia.org/wiki/List_of_rulers_of_Bhutan#/media/File:Bhutan-Jigme-Wangchuck.jpg",
    "Jose Luis Tejada Sorzano, Bolivian Republic": "https://www.ibolivia.org/wp-content/uploads/2019/09/jose-luis-tejada-sorzano.jpg",
    "Getulio Vargas, Brazil": "https://www.historynet.com/wp-content/uploads/2022/10/getulio-vargas-brazilian-president-mh-winter-2023-1021x1536.jpg",
    "Shenton Thomas, British Malaya": "https://collectionimages.npg.org.uk/large/mw52645/Sir-Thomas-Shenton-Whitelegge-Thomas.jpg",
    "Willingdon (Linlithgow in game - he didn't become the governor until April), British Raj": "https://en.wikipedia.org/wiki/Freeman_Freeman-Thomas,_1st_Marquess_of_Willingdon#/media/File:Freeman_Freeman-Thomas_by_Henry_Walter_Barnett.jpg",
    "Boris III, Bulgaria": "https://cdn.britannica.com/43/76543-050-237F3206/Boris-III.jpg",
    "William Mackenzie King, Dominion of Canada": "https://d2kdkfqxnvpuu9.cloudfront.net/images/giant/78031.jpg?1532342723",
    "Arturo Alessandri, Chile": "https://media.lex.dk/media/158030/standard_Arturo_Alessandri_Palma_en_1925.jpg",
    "Chiang Kai-Shek, China": "https://2.bp.blogspot.com/-EB8nDjZEwJI/TuAY0WNSpyI/AAAAAAAAC50/7zK7Yufv7J8/s1600/Chiang+Kai-shek+V.jpg",
    "Colombia": "https://farm5.staticflickr.com/4113/5184941825_8360a39cfc_z.jpg",
    "Mao Zedong, Communist China": "https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/mao-tse-tung-portrait-bettmann.jpg",
    "Ricardo Jimenez Oreamuno, Costa Rica": "https://prabook.com/web/show-photo.jpg?id=1500768",
    "Jose Agripino Barnet, Cuba": "https://historymaps.info/images/1940.png",
    "Edvard Benes, Czechoslovakia": "https://media.gettyimages.com/photos/portrait-of-czechoslovakian-politician-edvard-benes-1930s-picture-id174305241?k=6&m=174305241&s=612x612&w=0&h=KQmlOb_sF6e-JvcCNfWmT26mdnhNHZqhM_dp5mfbsA8=",
    "Thorvald Stauning, Denmark": "https://media.snl.no/media/194379/standard_Stauning_i1920-erne_1_.jpg",
    "Rafael Trujillo, Dominican Republic": "https://i5.walmartimages.com/asr/60b4ab9c-c6e2-4790-bc93-51c2f8f2d612_1.aa405431017ddccb483e52b088e7f477.jpeg",
    "Bonifacius Cornelis de Jonge, Dutch East Indies": "https://en.wikipedia.org/wiki/Bonifacius_Cornelis_de_Jonge#/media/File:Portrait_of_Jonkheer_Bonifacius_Cornelis_de_Jonge_by_Jan_Frank_Ministry_of_the_Interior_and_Kingdom_Relations.jpg",
    "Federico Paez, Ecuador": "https://www.enciclopediadelecuador.com/wp-content/uploads/2016/05/Ing_Federico_Paez.jpg",
    "Maximiliano Hernandez Martinez, El Salvador": "https://media.gettyimages.com/photos/portrait-between-approximately-1931-and-1937-of-the-general-and-of-picture-id105218372?k=6&m=105218372&s=612x612&w=0&h=grCdkAaTFGtCFWnXHNfXmPSEt_2Ozxm8ywDSg9UOkjE=",
    "Konstantin Pats, Estonia": "https://media.gettyimages.com/photos/portrait-of-estonia-head-of-state-konstantin-pats-1939-picture-id505811222?k=6&m=505811222&s=612x612&w=0&h=t16YheBgylYNXbYo-3UO3w4IV_5ttQpxot1qf_zEPUY=",
    "Haile Selassie, Ethiopia": "http://bih-x.info/wp-content/uploads/2017/08/Haile-Selassie.jpg",
    "Pehr Evind Svinhufvud, Finland": "https://en.wikipedia.org/wiki/List_of_presidents_of_Finland#/media/File:President_of_Finland_Pehr_Evind_Svinhufvud.jpg",
    "Konstantinor Demertzis, Kingdom of Greece": "https://alchetron.com/cdn/konstantinos-demertzis-db250750-a860-484b-86b3-e8d9071292a-resize-750.jpg",
    "Li Zongren, Guangxi Clique": "https://p5.toutiaoimg.com/details/v1/w640/pgc-image/dafc0fd1011142a095fbf7703c727b67.awebp?from=detail",
    "Jorge Ubico, Guatemala": "https://en-academic.com/pictures/enwiki/71/General-Jorge-Ubico.jpg",
    "Stenio Vincent, Haiti": "https://alchetron.com/cdn/stnio-vincent-949bd4cd-d1d8-4109-b3ee-27a82b0debd-resize-750.jpeg",
    "Tiburcio Carias Andino, Honduras": "https://media.gettyimages.com/id/514908104/photo/general-tiburcio-andino-honduran-president.jpg?s=1024x1024&w=gi&k=20&c=b0-ttljHIEMaVWFLrbXBmhbw0l1QXOL7VQWakgOC46k=",
    "Miklos Horthy, Kingdom of Hungary": "https://cdn.prod.www.spiegel.de/images/2fcf1502-0001-0004-0000-000001242238_w1600_r0.718_fpx50_fpy61.74.jpg",
    "Hermann Jonasson, Iceland": "https://www.althingi.is/myndir/mynd/thingmenn/249/org/mynd.jpg",
    "Reza Shah, Iran": "https://en.wikipedia.org/wiki/Reza_Shah#/media/File:Reza_shah_uniform.jpg",
    "Yasin al-Hashimi, Iraq": "https://en.wikipedia.org/wiki/Yasin_al-Hashimi#/media/File:Yasin_Hashimi,_1927.jpg",
    "Eamon de Valera, Ireland": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/De_Valera_LCCN2016822004_(headshot).jpg/640px-De_Valera_LCCN2016822004_(headshot).jpg?Eamon_de_Valera66281741",
    "Alberts Kviesis, Latvia": "https://www.famousbirthdays.com/faces/kviesis-alberts-image.jpg",
    "Edwin Barclay, Liberia": "https://vignette.wikia.nocookie.net/kaiserreich/images/7/79/EdwinBarclay.jpeg/revision/latest/scale-to-width-down/210?cb=20200611191349",
    "Antanas Smetona, Lithuania": "https://i5.walmartimages.com/asr/afe752c6-fd31-4f37-9111-12b0603f9d4a_1.9238b9b31b564536b4a946692dcc356f.jpeg",
    "Joseph Bech, Luxembourg": "https://media.snl.no/media/56549/standard_Joseph_Bech_1933.jpg",
    "Puyi, Manchukuo": "https://en.wikipedia.org/wiki/Puyi#/media/File:Pu_Yi,_Qing_dynasty,_China,_Last_emperor.jpg",
    "Yondonwangchug, Mengkukuo (Technically at time was Mongol Military Government)": "https://kids.kiddle.co/images/b/bd/Yun_Wang.jpg",
    "Lazaro Cardenas del Rio, Mexico": "https://www.thoughtco.com/thmb/RCIk6dZvUoVbdHvE1mnTmbgXdUo=/2566x3680/filters:fill(auto,1)/General_L-zaro_C-rdenas_del_R-o-56a58abb3df78cf77288ba9d.jpg",
    "Anandyn Amar, Mongolia": "https://pantheon.world/images/profile/people/1273444.jpg",
    "Tribhuvan Bir Bikram Shah, Nepal": "https://en.wikipedia.org/wiki/Tribhuvan_of_Nepal#/media/File:King_Tribhuvan_(cropped).png",
    "Hendrikus Colijn, Netherlands": "https://images0.persgroep.net/rcs/oigqgROv9uQBK91JADu-v_CwmMA/diocontent/201479807/_fitwidth/763?appId=93a17a8fd81db0de025c8abd1cca1279&quality=0.8",
    "Michael Joseph Savage, New Zealand": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Michael_Joseph_Savage_Portrait_(cropped).jpg/440px-Michael_Joseph_Savage_Portrait_(cropped).jpg",
    "Juan Bautista Sacasa, Nicaragua": "https://en.wikipedia.org/wiki/Juan_Bautista_Sacasa#/media/File:Juan_Bautista_Sacasa_cph.3a44780.jpg",
    "Johan Nygaardsvold, Norway": "https://en.wikipedia.org/wiki/Johan_Nygaardsvold#/media/File:Johan_Nygaardsvold_1934.jpeg",
    "Said bin Taimur, Oman": "https://en.wikipedia.org/wiki/Said_bin_Taimur#/media/File:Said_bin_Taimur_(cropped).png",
    "Harmodio Arias Madrid, Panama": "https://www.biografiasyvidas.com/biografia/a/fotos/arias_harmodio.jpg",
    "Eusebio Ayala, Republic of Paraguay": "https://en.wikipedia.org/wiki/Eusebio_Ayala#/media/File:Eusebio_Ayala_retrato.jpg",
    "Oscar Benavides, Peru": "https://prabook.com/web/show-photo.jpg?id=1500255",
    "Manuel Quezon, Philippines": "https://en.wikipedia.org/wiki/Manuel_L._Quezon#/media/File:Manuel_L._Quezon_(November_1942).jpg",
    "Ignacy Moscicki, Poland": "https://cdn.britannica.com/12/133912-050-133E81E8/Ignacy-Moscicki.jpg",
    "Antonio de Oliveira Salazar, Portugal": "https://c1.staticflickr.com/9/8218/8313183867_b9d1de79ec_b.jpg",
    "Gheorghe Tatarescu, Romania": "https://alchetron.com/cdn/gheorghe-ttrescu-09891028-e2aa-4020-b897-206cf23372f-resize-750.jpeg",
    "Ibn Saud, Saudi Arabia": "https://cdn.britannica.com/35/10835-050-F37ECEB0/Ibn-Saud-kingdom-Saudi-Saudi-Arabia-country.jpg",
    "Yan Xishan, Shanxi": "https://en.wikipedia.org/wiki/Yan_Xishan#/media/File:Yan_Xishan.jpg",
    "Phraya Phahon Phonphayuhasena, Siam": "https://i.pinimg.com/originals/11/30/e2/1130e27b15593ac0ad260f012dceb4fa.jpg",
    "Ma Zhongying, Sinkiang": "https://alchetron.com/cdn/ma-zhongying-141792d0-9d79-41ab-95e9-3c72a08994e-resize-750.jpg",
    "J.B.M. Hertzog, South Africa": "https://vignette.wikia.nocookie.net/totalwar-ar/images/2/29/J.B.M._Hertzog.jpg/revision/latest?cb=20180520204722",
    "Francisco Franco, Spain": "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-760w,f_auto,q_auto:best/newscms/2019_39/3023096/190924-francisco-franco-cs-735a.jpg",
    "Axel Pehrsson-Bramstorp, Sweden": "https://en.wikipedia.org/wiki/Axel_Pehrsson-Bramstorp#/media/File:Axel_Pehrsson-Bramstorp.jpg",
    "Albert Meyer, Switzerland": "https://prabook.com/web/show-photo.jpg?id=23913",
    "Adyg Tyulush Chulydum (no picture), Tannu Tuva": "https://qph.cf2.quoracdn.net/main-qimg-9ffd1ef7ec255b2a468710921dcd3bce",
    "Jamphel Yeshe Gyaltsen, Tibet": "https://qph.cf2.quoracdn.net/main-qimg-9ffd1ef7ec255b2a468710921dcd3bce",
    "Mustafa Kemel Ataturk, Turkey": "https://www.thoughtco.com/thmb/YkmGSzPhLqf1sAqVyO2m19jpSiE=/2537x3775/filters:fill(auto,1)/AtaturkCentralPressGettyImages1925-56a040965f9b58eba4af89b5.jpg",
    "Gabriel Terra, Uruguay": "https://el-pais.brightspotcdn.com/uploads/2019/06/21/5d0d4acf1d704.jpeg",
    "Eleazar Contreras, Venezuela": "https://www.biografiasyvidas.com/biografia/l/fotos/lopez_contreras.jpg",
    "Xibei San Ma": "https://de-academic.com/pictures/dewiki/77/Ma_Bufang.jpg",
    "Imam Yahya, Yemen": "https://en.wikipedia.org/wiki/Yahya_Muhammad_Hamid_ed-Din#/media/File:Imam_yahya_cropped.png",
    "Prince Paul, Yugoslavia": "https://en.wikipedia.org/wiki/Prince_Paul_of_Yugoslavia#/media/File:Prince_Paul_of_Yugoslavia.jpg",
    "Li Yuanhong, Yunnan": "https://en.wikipedia.org/wiki/Li_Yuanhong#/media/File:Li_Yuanhong.jpg"  
}

HISTORICAL_EMPIRES = {
    "German Empire": {
        "description": "Description: The German Empire reached its peak in 1914, encompassing much of Central Europe and parts of Northern Europe. It was a major European power until its defeat in World War I.\n\nScenario: Choose Germany and go through the Monarchist path to restore the glory to the German Empire. Make Bismarck proud! This is realpolitik and weltpolitik at its finest. Reclaim lost territories and bring back the glory of the Kaiserreich!",
        "image": "https://cdn.britannica.com/04/904-050-BE947E27/German-Empire-1918.jpg",
    },
    "Austro-Hungarian Empire": {
        "description": "Description: The Austro-Hungarian Empire was the last remnant of the Holy Roman Empire, existing from 1867 until its dissolution in 1918. It was a multi-ethnic empire in Central and Southeastern Europe.\n\nScenario: Choose Austria and go down either the Monarchist or Fascist path to restore the Austro-Hungarian Empire. Unite the diverse peoples under a single banner! Can you stave off ethnonationalism and restore the glory of the Habsburgs?",
        "image": "https://i.pinimg.com/originals/03/03/df/0303dfedef611ad07008cf2af2fbfa33.jpg",
    },
    "Ottoman Empire": {
        "description": "Description: The Ottoman Empire was a vast and powerful empire that lasted from 1299 to 1922, covering parts of Europe, Asia, and Africa. It was known for its cultural diversity and military prowess.\n\nScenario: Choose Turkey and go down the Authoritarian path to restore the Ottoman Empire. Reclaim lost territories and bring back the glory of the Ottomans! The Sultanate awaits you!",
        "image": "https://www.liberatingnarratives.com/content/images/size/w1460/2022/12/Ottoman-Empire-Contraction-1.jpg",
    },
    "Russian Empire (Pre-Brest-Litovsk)": {
        "description": "Description: The Russian Empire was one of the largest empires in history, existing from 1721 until the abdication of Tsar Nicholas II in 1917. It extended as far west as Poland and as far east as Alaska.\n\nScenario: Choose Russia and go down the Monarchist path to restore the Russian Empire. Reclaim lost territories and bring back the glory of the Tsars! Fulfill the dreams of Peter the Great to advance Russia into western Europe!",
        "image": "https://www.historicpictoric.com/cdn/shop/products/563545_1wmark.jpg?v=1683485705",
    },
    "Qing Dynasty": {
        "description": "Description: The Qing Dynasty was the last imperial dynasty of China, ruling from 1644 to 1912. It was known for its territorial expansion and cultural achievements.\n\nScenario: Choose ideally Manchukuo and go down its authoritarian path to restore the Qing Dynasty. Reclaim lost territories and bring back the glory of the Qing Emperors [except that one child emperor]! (You can also choose China and go down the Fascist path to restore the Qing Dynasty, but it is not recommended. *It doesn't give any ability to core the Qing territories.*)",
        "image": "https://i.pinimg.com/originals/f8/64/67/f86467b95e21772e55931e1949d910af.jpg"
    },
    "Roman Empire": {
        "description": "Description: Let's be honest, the Roman Empire is the most famous empire in history. It was a vast empire that dominated much of Europe, North Africa, and the Middle East from 27 BC to AD 476.\n\nScenario: Choose Italy and go down either the Fascist or Monarchist path to restore the Roman Empire. Bring back the Caesars and reclaim the Mediterranean!",
        "image": "https://i.pinimg.com/originals/5a/e5/78/5ae578b225dad65524298833d65bbceb.jpg",
    },
    "Holy-Roman Empire": {
        "description": "Description: Voltaire said \"The Holy Roman Empire was neither holy, nor Roman, nor an empire.\" Surely being led by emperors for centuries earns it the place of an empire? With the Pope as its spiritual leader, surely it was holy? Regardless, the Holy Roman Empire and its numerous states and principalities existed from 800 to 1806, covering much of Central Europe.\n\nScenario: Choose Germany or Austria and go down the Monarchist path to restore the Holy Roman Empire. Reclaim lost territories and bring back the glory of the HRE! Unite the Germanic peoples under a single banner!",
        "image": "https://brilliantmaps.com/wp-content/uploads/Holly-Roman-Empire-Max.png",
    },
    "Napoleonic Empire": {
        "description": "Description: Despite being short-lived, the Napoleonic Empire is probably the second-most famous empire in history second only to Rome. Napoleon Bonaparte's empire existed from 1804 to 1814, covering much of Europe and parts of North Africa.\n\nScenario: Choose France and go down the Monarchist path to restore the Napoleonic Empire. Reclaim lost territories and bring back the glory of Napoleon! Make France the dominant power in Europe once again! Fulfill the dreams of Napoleon Bonaparte to make France a superpower!",
        "image": "https://images.squarespace-cdn.com/content/v1/5f87a249e7f9db54f33b0228/1632747832936-ORTGEKQWTVIHICHZNAB7/french+empire+2.jpeg",
    },
    "Byzantine Empire": {
        "description": "Description: The Byzantine Empire was the continuation of the Roman Empire in the East during the Middle Ages. It was known for its rich culture, art, and architecture, as well as its complex political history.\n\nScenario: Choose Greece and go down the Monarchist path to restore the Byzantine Empire. Reclaim lost territories and bring back the glory of the Byzantine Emperors!",
        "image": "https://us-static.z-dn.net/files/d86/be685da8e577f6427acaa9b55a7f3f38.png",
    },
    "Macedonian Empire": {
        "description": "Description: The Macedonian Empire was established by Alexander the Great in the 4th century BC. It is known for its military conquests and the spread of Greek culture across three continents.\n\nScenario: Choose Greece and go down the Monarchist path to restore the Macedonian Empire. Reclaim lost territories and bring back the glory of Alexander the Great! Hellenize the Middle East and bring about the era of the Macedons!",
        "image": "https://mmsdragon.org/wp-content/uploads/2021/05/main-qimg-a3c395fb8f6941e61b893df71ca61b7b.jpg",
    },
    "Carolingian Empire": {
        "description": "Description: The Carolingian Empire was a Frankish state that emerged in the 8th century under the leadership of Charlemagne. It is known for its cultural and political achievements, as well as its role in the formation of modern Europe.\n\nScenario: Choose France and go down the Monarchist path to restore the Carolingian Empire. Reclaim lost territories and bring back the glory of Charlemagne!",
        "image": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e3ef8fc3-b414-4e15-9071-1afbb9b834a7/dfs56a3-0bfc7d53-0f54-4538-9c7b-1909eda772ff.png/v1/fill/w_1192,h_670/charlemagne_and_the_carolingian_empire_814_by_sergiulusardu_dfs56a3-pre.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvZTNlZjhmYzMtYjQxNC00ZTE1LTkwNzEtMWFmYmI5YjgzNGE3XC9kZnM1NmEzLTBiZmM3ZDUzLTBmNTQtNDUzOC05YzdiLTE5MDllZGE3NzJmZi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.mb6innGxSeeYwGouv-_VtUrH5y_B5WKMx2qdQge7Www",
    },
    "Achaemenid Empire": {
        "description": "Description: The Achaemenid Empire, also known as the First Persian Empire, was the first great Persian Empire, founded by Cyrus the Great in the 6th century BC. It is known for its vast territorial expansion and cultural achievements.\n\nScenario: Choose Iran and go down the Monarchist or Fascist path to restore the Achaemenid Empire. Reclaim lost territories and bring back the glory of Cyrus the Great! Unite the Persian peoples under a single banner!",
        "image": "https://realhistoryww.com/world_history/ancient/Maps/Map_Achaemenid_empire.jpg",
    },
    "Kalmar Union": {
        "description": "Description: The Kalmar Union was a series of personal unions that united the kingdoms of Denmark, Norway, and Sweden under a single monarch in the late 14th century. It is known for its attempts to create a unified Scandinavian realm.\n\nScenario: Choose Sweden and go down the Monarchist path to restore the Kalmar Union. Reclaim lost territories and bring back the glory of the united Nordic kingdoms!",
        "image": "https://cdn.thecollector.com/wp-content/uploads/2024/07/kalmar-union-map-1024x1024.jpg",
    },
    "Arab Caliphate": {
        "description": "Description: The Arab Caliphate was a series of Islamic states that emerged in the 7th century, following the death of the Prophet Muhammad. It is known for its cultural and scientific achievements, as well as its territorial expansion across the Middle East, North Africa, and parts of Europe.\n\nScenario: Choose Iraq or any other Middle Eastern nations and go down the Monarchist or Fascist paths to restore the Arab Caliphate. Reclaim lost territories and bring back the glory of the Caliphs! Unify the Arab world under a single banner!",
        "image": "https://smarthistory.org/wp-content/uploads/2021/12/Abbasid_Caliphate_850AD-copy.jpg"
    }
}