
LightsaberList = [
    "{user1} thrusts their lightsaber at {user2}.",
    "{user1} ignites their lightsaber with a menacing hum, advancing toward {user2}.",
    "{user1} channels the Force to pull their lightsaber just in time to block {user2}'s strike.",
    "{user1} twirls their lightsaber, creating a dazzling display of light, before lunging at {user2}.",
    "{user1} swings low, aiming for {user2}'s legs, forcing {user2} to jump back.",
    "{user1} quotes an old Jedi text while {user2} rolls their eyes and attacks.",
    "{user1} and {user2} lock blades, sparks flying as each tries to overpower the other.",
    "{user1} uses the Force to send a pebble at {user2}, just enough of a distraction to land a glancing blow.",
    "{user1} performs a high spin, their lightsaber casting arcs of blue light as {user2} parries.",
    "{user1} mutters, 'I have the high ground,' confusing {user2} for a brief moment.",
    "{user1} deactivates their lightsaber mid-swing, confusing {user2} just long enough to reignite it and strike.",
    "{user1} uses the Force to throw debris at {user2}, creating an opening for a strike.",
    "{user1}'s lightsaber hums as they twirl it defensively, deflecting every blow {user2} makes.",
    "{user1} and {user2} engage in a furious saber lock, faces illuminated by the glow of plasma.",
    "{user1} executes a perfect saber spin, narrowly avoiding {user2}'s relentless strike.",
    "{user1} taps into the dark side, releasing a wave of energy that pushes {user2} back.",
    "{user1} flourishes their saber with a dramatic twirl. 'The Force is strong with me,' they declare.",
    "{user1} lunges forward, their lightsaber crackling as it clashes with {user2}'s weapon.",
    "{user1} jumps high, flipping over {user2} and landing with a quick slash.",
    "{user1} adjusts their stance. 'Only a Sith deals in absolutes,' they quip before striking at {user2}.",
    "{user1} flicks their wrist, creating a blinding flash of light to disorient {user2} momentarily.",

]

CutlassList = [
    "{user1} distracts {user2} by gesturing at a parrot.",
    "{user1} swings from a nearby rope, cutlass in hand, screaming a hearty 'YARRR!' as they land near {user2}.",
    "{user1} raises their cutlass high, challenging {user2} to a duel in front of a cheering crowd of pirates.",
    "{user1} taps their cutlass against {user2}'s blade, grinning. 'A fine day to be plunderin'!' they declare.",
    "{user1} ducks behind a barrel, tossing rum at {user2} before leaping out with a wild slash.",
    "{user1} and {user2} circle each other, cutlasses clanging in a deadly dance of steel.",
    "{user1} tosses a handful of sand at {user2}'s eyes and follows up with a quick swipe.",
    "{user1} laughs as they parry {user2}'s blow, 'You fight like a landlubber!'",
    "{user1} clinks their cutlass against {user2}'s. 'To the depths with ye!' they shout as they press the attack.",
    "{user1} grabs a flagon of ale mid-duel, taking a swig before barely blocking {user2}'s strike.",
    "{user1} points behind {user2} and yells 'Kraken!' while attempting a sneaky stab.",
    "{user1} swings their cutlass in a wide arc, shouting, 'To Davy Jones with ye!' as they press {user2}.",
    "{user1} distracts {user2} by tossing a bag of coins, then strikes with a gleam in their eye.",
    "{user1} and {user2} lock blades, the sea breeze whipping around them as the ship creaks.",
    "{user1} kicks a barrel at {user2}'s feet before lunging with their cutlass.",
    "{user1} raises an eyebrow, 'Care for a wager?' they ask, parrying {user2}'s attack with ease.",
    "{user1} swings low, aiming for {user2}'s legs, but {user2} leaps nimbly over the cutlass.",
    "{user1} laughs, 'Ye fight like a sea slug!' and takes another swing at {user2}.",
    "{user1} clambers up the rigging, daring {user2} to follow, all while twirling their cutlass.",
    "{user1} and {user2} trade insults while circling each other, blades flashing in the sunlight.",
    "{user1} bites down on a knife as they duel with their cutlass in hand, striking fear into {user2}.",
]

BroadswordList = [
    "{user1} slices through the air at {user2} who blocks.",
    "{user1} charges forward with a battle cry, their broadsword poised to strike {user2}.",
    "{user1} and {user2} clash, broadswords ringing with the weight of their blows.",
    "{user1} swings their broadsword overhead, aiming a crushing blow at {user2}.",
    "{user1} steps back, using their shield to deflect {user2}'s powerful slash.",
    "{user1} exchanges a knowing nod with {user2} before resuming their fierce duel.",
    "{user1} twirls their broadsword in a fancy flourish before lunging at {user2}.",
    "{user1} drops to one knee, deflecting {user2}'s strike upward before countering.",
    "{user1} challenges {user2} to fight honorably before promptly kicking dirt at them.",
    "{user1} feints left, then strikes right, testing {user2}'s defenses.",
    "{user1} lets out a hearty laugh, 'You call that a strike? Let me show you true steel!'",
    "{user1} roars a battle cry, charging toward {user2} with their broadsword held high.",
    "{user1} shifts their weight, catching {user2}'s strike on their broad shield.",
    "{user1} locks swords with {user2}, inches away from each other's faces as they grapple.",
    "{user1} swings their broadsword in a wide, sweeping arc that forces {user2} to backpedal.",
    "{user1} bashes {user2} with their pommel, gaining a momentary advantage.",
    "{user1} spins their broadsword, daring {user2} to make the first move.",
    "{user1} fights valiantly, 'For honor and glory!' they cry, matching {user2} blow for blow.",
    "{user1} stomps the ground, sending a small shockwave that disrupts {user2}'s stance.",
    "{user1} catches {user2}'s blade with a gauntlet, using sheer strength to push back.",
    "{user1} grits their teeth, 'No quarter!' they shout, pressing their attack on {user2}.",
]

MartialArtsList = [
    "{user1} does a roundhouse kick at {user2}.",
    "{user1} assumes a ready stance, eyes focused intently on {user2}'s every move.",
    "{user1} executes a flawless spinning back kick, barely missing {user2}'s nose.",
    "{user1} and {user2} exchange rapid blows, fists and feet a blur of motion.",
    "{user1} sidesteps {user2}'s punch, redirecting their momentum into a roll.",
    "{user1} channels their energy, unleashing a powerful kiai as they strike.",
    "{user1} offers {user2} a respectful bow before sweeping their legs.",
    "{user1} strikes with a palm thrust, knocking {user2} off balance.",
    "{user1} counters {user2}'s move with an expertly-timed elbow strike.",
    "{user1} catches {user2}'s kick and spins, sending {user2} stumbling backward.",
    "{user1} pauses mid-fight to adjust their gi, dodging {user2}'s attack at the last second.",
    "{user1} executes a lightning-fast jab combination, keeping {user2} on the defensive.",
    "{user1} leaps into a spinning tornado kick aimed at {user2}'s shoulder.",
    "{user1} channels their chi, steadying their breathing as they face {user2}.",
    "{user1} ducks low, sweeping {user2}'s legs out from under them.",
    "{user1} catches {user2}'s punch and counters with an open palm strike.",
    "{user1} unleashes a barrage of quick kicks, forcing {user2} to block or retreat.",
    "{user1} and {user2} clash, their movements fluid and precise, like a well-rehearsed dance.",
    "{user1} performs a backflip to create distance before charging at {user2}.",
    "{user1} takes a moment to bow, then launches into a flurry of strikes.",
    "{user1} parries {user2}'s punch and uses an arm lock to gain control.",
]