SKILLSLIST = {
    "Piano": [0, 0, "Electric Piano", "Grand Piano"],
    "Guitar": [0, 0, "Guitar"],
    "Singing": [0, 0],
    "Art": [0, 0, "Easel"],
    "Photography": [0, 0, "Photo Camera"],
    "Comedy": [0, 0],
    "Charisma": [0, 0],
    "Writing": [0, 0, "Laptop", "Notebook", "Desktop"],
    "Handiness": [0, 0, "Toolbox"],
    "Woodworking": [0, 0, "Toolbox"],
    "Programming": [0, 0, "Laptop", "Desktop"],
    "Science": [0, 0, "Science workstation"],
    "Medicine": [0, 0, "Skeleton study tool", "Medical Textbook"],
    "Fishing": [0, 0, "Fishing rod"],
    "Gardening": [0, 0, "Gardening tools"],
    "Cooking": [0, 0, "Stove"],
    "Acting": [0, 0],
    "Baking": [0, 0, "Stove"]
}
