
SKILLSLIST = {
    "Piano": [0, 0, ["Music Enthusiast"], ["Electric piano", "Grand piano"]],
    "Guitar": [0, 0, ["Music Enthusiast"], ["Guitar"]],
    "Singing": [0, 0, ["Music Enthusiast"]],
    "Art": [0, 0, ["Art Connoisseur", "Perfectionist", "Eccentric"], ["Easel", "Canvas"]],
    "Photography": [0, 0, ["Art Connoisseur", "Perfectionist", "Eccentric"], ["Photo camera"]],
    "Comedy": [0, 0, ["Witty Comedian", "Sarcastic"]],
    "Charisma": [0, 0, ["Charismatic", "Empathic"]],
    "Writing": [0, 0, ["Literary Aficionado", "Perfectionist"], ["Laptop", "Notebook", "Desktop"]],
    "Handiness": [0, 0, ["Skilled Craftsperson", "Perfectionist"], ["Toolbox", "Workbench"]],
    "Woodworking": [0, 0, ["Skilled Craftsperson", "Perfectionist"], ["Toolbox", "Workbench"]],
    "Programming": [0, 0, ["Tech Savant", "Logical"], ["Laptop", "Desktop"]],
    "Science": [0, 0, ["Science Savant", "Inquisitive", "Logical"], ["Science workstation", "Microscope"]],
    "Medicine": [0, 0, ["Science Savant", "Inquisitive", "Logical"], ["Skeleton study tool", "Medical textbook"]],
    "Fishing": [0, 0, ["Sea-born"], ["Fishing rod"]],
    "Gardening": [0, 0, ["Green Thumb"], ["Gardening tools"]],
    "Cooking": [0, 0, ["Culinary Artisan"], ["Stove"]],
    "Acting": [0, 0, ["Natural-born performer", "Empathic"], ["Movie script"]],
    "Baking": [0, 0, ["Culinary Artisan"], ["Stove"]],
    "Athletic": [0, 0, ["Energetic Dynamo", "Fierce Competitor"]],
    "Social Media": [0, 0, ["Charismatic", "Chronically Online"]],
    "Logic": [0, 0, ["Logical", "Inquisitive"], ["Chess board", "Logic puzzles"]],
    "Debate": [0, 0, ["Persuasive", "Charismatic"], ["Casebook"]],
    "Mischief": [0, 0, ["Mischief Maker", "Witty Comedian"], ["Whoopie cushion"]],
    "Sewing": [0, 0, ["Fashion Forward", "Perfectionist"], ["Sewing machine", "Fabric"]],
    "Force-wielding": [0, 0, ["Force-sensitive"], ["Force Tome"]],
    "Dueling": [0, 0, ["Quick footed", "Fierce Competitor"], ["Lightsaber", "Cutlass", "Broadsword", "Practice Dummy"]],
    "Sailing": [0, 0, ["Sea-born", "Adventurous"], ["Dinghy", "Sailboat", "Frigate"]],
    "Martial Arts": [0, 0, ["Quick footed", "Athletic", "Fierce Competitor"], ["Training Mat"]],
    "Gaming": [0, 0, ["Gamer", "Fierce Competitor"], ["A PS5", "Laptop", "Desktop"]],
    "Swimming": [0, 0, ["Sea-born", "Energetic Dynamo"]]
}

