TRAITS = {
    "Music Enthusiast": "Loves all things music, from composing to attending concerts. Gains faster skill with music-related activities and instruments.",
    "Art Connoisseur": "Has a keen eye for beauty and aesthetics, appreciating art in all forms. Boosts creativity and gains art skills faster.",
    "Science Savant": "Thrives on scientific knowledge and experimentation. Gains science-related skills more efficiently.",
    "Witty Comedian": "Always ready with a joke, bringing humor into any situation. Gains comedy skills faster and better at telling jokes.",
    "Social Butterfly": "Enjoys meeting new people and thrives in social settings. Gains charisma quickly and loves building a network of people.",
    "Literary Aficionado": "Has a deep love for literature and writing. Gains skill in writing much faster.",
    "Skilled Craftsperson": "Expert at building or repairing things. Gains crafting or mechanical skills at an accelerated pace.",
    "Driven Achiever": "Sets high goals and works tirelessly to reach them. Gains experience faster in any career.",
    "No-nonsense": "Prefers getting straight to the point without any emotions slowing them down.",
    "Elitist": "Holds high standards and often looks down on “lesser” pursuits.",
    "Green Thumb": "Has a natural talent for gardening and working with plants. Gains gardening skills quicker.",
    "Friendly": "Friendly and approachable, often bringing positivity to those around them. Gains social trust faster.",
    "Grumpy": "Prone to negative moods and complaints. Will have more trouble in relationships.",
    "Loner": "Prefers alone time, often in deep thought. Would prefer to not be in social settings.",
    "Force-sensitive": "Sensitive to mysterious, otherworldly forces. Gains bonuses to force-wielding skills.",
    "Mischief Maker": "Loves causing harmless trouble and pranks. Gains trickster-related abilities and social stealth.",
    "Culinary Artisan": "Natural talent in the kitchen, making every dish memorable. Gains cooking skills quickly.",
    "Energetic Dynamo": "Always on the move, full of energy. Gains fitness skills faster and excels in active pursuits.",
    "Charismatic": "Magnetic presence that draws people in. Gains bonuses in social negotiations and influence.",
    "Fashion Forward": "Has a flair for style and trends. Gains influence in fashion.",
    "Tech Savant": "Expert in technology and programming. Gains computer and tech-related skills quickly.",
    "Thrifty": "Great at saving money and making the most of limited resources.",
    "Chronically Online": "Thrives on social media fame and recognition.",
    "Thrill Seeker": "Loves taking risks and trying daring feats.",
    "Valiant": "Brave and committed to bringing values into their lives.",
    "Absent-Minded": "Prone to daydreaming or forgetting things. Gains bursts of creativity but struggles with focus.",
    "Business Tycoon": "Natural talent for commerce and profit.",
    "Shadowy Operative": "Prefers moving unseen and being elusive.",
    "Neat Freak": "Obsessed with cleanliness and order. Gains efficiency in organizational tasks.",
    "Messy": "Often disorganized.",
    "Curious Investigator": "Loves asking questions and uncovering the unknown.",
    "Flirtatious": "Naturally inclined toward romantic interactions. Succeeds more often at romantic interactions.",
    "Empathic": "Deeply attuned to others’ emotions.",
    "Sarcastic": "Sharp wit with a sarcastic edge. Gains influence in conversations but can offend easily.",
    "Fierce Competitor": "Driven by winning and being the best.",
    "Explorer": "Drawn to new experiences and places.",
    "Animal Friend": "Deep bond with animals.",
    "Gamer": "Skilled at gaming.",
    "Hoarder": "Loves collecting and preserving items.",
    "Reckless": "Often acts on impulse without thinking.",
    "Skeptic": "Always wary of hidden motives. Struggles with trust.",
    "Pessimist": "Focuses on potential downsides. Gains resistance to disappointment but lacks enthusiasm.",
    "Night Owl": "Most active and productive at night. Gains efficiency boosts during late hours.",
    "Lucky": "Frequently lucky in events. Gains chance-based rewards more often.",
    "Perfectionist": "Strives for flawlessness in everything.",
    "Quirky": "Stands out for unusual interests or behavior.",
    "Defiant Rebel": "Dislikes rules and norms.",
    "Workaholic": "Invests deeply in work. Gains fast career progress but risks burnout.",
    "Brooding Thinker": "Reflects deeply and feels deeply.",
    "Spiritual": "Pursues spiritual understanding.",
    "Clever Crafter": "Innovates with materials and items. Gains skill boosts in crafting.",
    "Peacekeeper": "Strives for harmony. Will avoid a fight at all costs.",
    "Short-Fused": "Quick to anger, but passionate.",
    "Dark-Hearted": "Manipulates for personal gain.",
    "Kind-Hearted": "Strives to help and support others. Gains bonuses in nurturing and team-building.",
    "Pirate": "Literally a pirate.",
    "Medieval": "Stuck in the medieval era.",
    "Sea-born": "Loves the sea and open waves. Will be better at sailing."
}